name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate documentation website
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: Writerside/adoc
          docker-version: 243.22562
        env:
          LOG_LEVEL: DEBUG

      - name: List generated files
        run: ls -R artifacts/

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: artifacts/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip website
        run: unzip artifacts/<actual-file-name>.zip -d site

      - name: Enable GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
