name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # 當推送到主分支時觸發
  workflow_dispatch:  # 支援手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate documentation website
        uses: JetBrains/writerside-github-action@v4
        with:
          config-path: Writerside/writerside.cfg  # 指定 writerside.cfg 路徑
        env:
          INSTANCE: Writerside/adoc  # 模組名稱和實例 ID（以 `/` 分隔）
          DOCKER_VERSION: 243.22562  # Writerside Docker 版本

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: out/  # 文檔輸出目錄

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip website
        run: unzip docs.zip -d site

      - name: Enable GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site  # 解壓後的網站資料夾

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
